version: '3'

services:
  postgres:
    image: postgres:14.8-alpine3.18

    environment:
      - POSTGRES_DB=galactic_market
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"